name: Generate OpenAPI Schema

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'backend/src/routes/**'
      - 'backend/src/controllers/**'
      - 'backend/src/models/**'
      - 'backend/config/swagger.js'
      - 'backend/docs/components.yaml'
      - 'backend/docs/paths.yaml'

jobs:
  generate-openapi:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
          
      - name: Install dependencies
        run: cd backend && npm ci
        
      - name: Generate OpenAPI schema
        run: cd backend && node scripts/generate-swagger.js
        
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add backend/docs/openapi.yaml
          
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "chore: update OpenAPI schema [skip ci]"
          git push 